//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashBoard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTR_Downtime
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> StopDate { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> CodeID { get; set; }
        public string Description { get; set; }
        public string Comment { get; set; }
        public Nullable<int> ProductionAreaID { get; set; }
        public Nullable<int> AssetID { get; set; }
        public Nullable<int> StationID { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public string CloseBy { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string RegBy { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public string CommingBy { get; set; }
        public Nullable<System.DateTime> CommingDate { get; set; }
        public Nullable<int> HardwareID { get; set; }
        public Nullable<int> DescriptionID { get; set; }
    
        public virtual TRC_dtProductionArea TRC_dtProductionArea { get; set; }
        public virtual DTR_DowntimeCode DTR_DowntimeCode { get; set; }
    }
}
