//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashBoard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAS_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FAS_Users()
        {
            this.FAS_PackingGS = new HashSet<FAS_PackingGS>();
        }
    
        public short UserID { get; set; }
        public string RFID { get; set; }
        public string UserName { get; set; }
        public bool IsActiv { get; set; }
        public byte UsersGroupID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAS_PackingGS> FAS_PackingGS { get; set; }
    }
}
