
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DashBoard.Models
{

using System;
    using System.Collections.Generic;
    
public partial class FAS_ShiftPlan
{

    public int ID { get; set; }

    public int LineID { get; set; }

    public short ShiftPlan { get; set; }

    public Nullable<short> ModelID { get; set; }



    public virtual FAS_Models FAS_Models { get; set; }

}

}
